### ISSUE TITLE
When pressing Ctrl+C - applet clears formula instead of copy to clipboard

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#33] opened 2020-05-26 09:28 UTC
When I pressing <kbd>Ctrl+C</kbd> - applet clears current input field with formula, instead of copy it to clipboard without modifying. Can you please fix this?

**Comment by dschopf** [comment] 2020-05-27 16:17
I thought this was already fixed in #25, apparently this is not the case. I will take a look.

**Comment by dschopf** [comment] 2020-05-27 16:40
The issue is pretty embarassing, already fixed in master. I have found another bug I would like to fix before making a new release. Should not take too long.

**Closed as completed** 2020-06-01 07:13 UTC

**Comment by MurzNN** [comment] 2020-06-01 08:37
Fixed, thanks!
